### ISSUE TITLE
Implement Internal Wave Progression & Tracking System

### ISSUE THREAD

**Issue by DrewsterJ** [DrewsterJ/Nameless-Defence#82]
- [x] The game keeps track of waves internally using a variable.
- [x] The game internally updates the wave number based on enemies killed.
- [x] The game provides a grace period between waves to transition to a new wave.
  - [x] Enemies stop spawning for a fixed time period.
- [x] The game starts at wave 1.
- [x] The game allows for an infinite number of waves.
